### ISSUE TITLE
Add button not sticky

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#59] opened 2016-05-17 19:18 UTC
The add post button can sometimes scroll up and down with the page, which should not happen

![img_3677](https://cloud.githubusercontent.com/assets/1618793/15336030/67a75118-1c29-11e6-891d-cdfb8f2c11b6.jpg)

**Comment by middle8media** [comment] 2016-07-15 09:24
I have tested and confirmed this bug is on mobile device only, not in browser. @brandonrosage any idea of what is going on here?

**Comment by stephengacheru** [comment] 2016-07-15 09:35
@middle8media It seems to be ok on my phone. Using google chrome on Android. Maybe it's specific to certain mobile browsers?

**Comment by middle8media** [comment] 2016-07-15 09:42
@stephengacheru I have tested on iPhone 6s with Chrome & Safari and can confirm this bug on both.

**Comment by middle8media** [comment] 2016-09-15 16:00
I am closing this because it is a browser/vendor bug. You will notice that when the browser moves its own toolbar out of the way it _then_ adjusts the viewport content, correcting the position of the button.

**Closed by middle8media** 2016-09-15 16:00 UTC
Labels: 2 - Design, Bug
